baseurl: "https://www.tottonsantarun.co.uk/"
title: "Totton SantaRun"
#canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-9232216-1"

params:
  # Conference info
  Name: "Totton Santa Run"
  Description: "A family friendly, Yuletide themed Fun Run with indoor near the line Fayre for runners and spectator enjoyment"
  Date: "9th December"
  Price: "Only:  Child £6, Adult £12, or Family £32 (two adults / two children)\n" # If your event is free, just comment this line
  Venue: "Empire Hall Totton"
  Address: "2 Salisbury Rd"
  City:  "Totton"
  State: "Southampton"
  Images: ["/img/runnerBacks.jpg"]
  GoogleMapsKey: "AIzaSyC6kc8cXGr1lkZdzKtCDivK2Oy0bJMTrIg"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - faqs
      #    - booking
    - schedule
    - entertainment
    - rules
    - sponsors
    # - partners
    # - contact
    # - speakers

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    faqs: "FAQs"
    # booking: "Booking"
    #speakers: "Speakers"
    schedule: "Schedule"
    entertainment: "Choirs"
    rules: "Cake off rules"
    sponsors: "Sponsors"
    #partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #  CallToAction:
  #  text: "Book now!"
  # link: "#booking"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "5th Testwood Scouts"
      logo: "/img/Logos/Scouts_Logo_Stack_Purple.jpg"
      url: "http://testwoodscouts.x10host.com/"

    - name: "New Forest Health and Leisure"
      logo: "/img/healthAndLeisure.png"
      url: "http://www.newforest.gov.uk/healthandleisure/"

    - name: "Electracare"
      logo: "/img/ElectraCareSq.jpg"
      url: "http://electracare.net/"

    - name: "Longman and Sons"
      logo: "/img/LongmanScoutsWebAdvertSq.jpg"
      url: "http://longmanandsons.com/"

    - name: "Fox Moving and Storage"
      logo: "/img/foxMoveingSq.jpg"
      url: "https://www.fox-moving.com/"

    - name: "Fast Forward Fitcamp"
      logo: "/img/fitcamp.jpg"
      url: "http://www.fastforward-fitcamp.co.uk/"

    - name: "Seadown Vets"
      logo: "/img/seadownVetsSq.png"
      url: "https://www.seadownvets.co.uk/"

    - name: "Boogie Bounce"
      logo: "/img/boogiebounce.jpg"
      url: "http://www.boogiebounce.com/cadnam-southampton-so40"

    - name: "Haydon Tyres"
      logo: "/img/haydon.png"
      url: "https://www.haydontyresandgarageservices.co.uk/"

    - name: "Jollyes Pet Superstore"
      logo: "/img/Jollyes.jpg"
      url: "https://www.jollyes.co.uk/totton"

  # List of Entertainment
  Entertainment:
    - name: "Ocean Harmony Chior"
      logo: "/img/oceanharmony.png"
      url: "https://oceanharmony.co.uk/"

    - name: "ROVERANG Alumni Choir"
      logo: "/img/roverang.png"
      url: "https://www.youtube.com/channel/UCEoklcNZwmTW0zBoWgTZChg"
  
  # List of Partners
  Partners:
    - name: "New Forest Health and Leisure"
      logo: "/img/healthAndLeisure.png"
      url: "http://www.newforest.gov.uk/healthandleisure/"

  # The entire schedule
  # 09:00 Runners only (Santacise with Boogie Bounce Southampton
  # 09:30 Christmas Fayre doors open / start of Santa Run
  # 10:00 Ocean Harmony Barbershop chorus performance
  # 11:00 Roverang Alumni Choir Performance
  # 11am -12pm Santa Selfies: get a picture of yourself with the big man himself
  # 12pm Mince Pie eating Competition
  # 12:10 Result of The Great Totton Cake Off
  # 12:30 The raffle is drawn (who will win this year’s hamper?)
  # 1:30 the Fayre closes
  # Craig  -  We are not using these but it is worth keeping incase we want to use/ modify them 
  Schedule:
    - name: "Santacise with Boogie Bounce Southampton"
      photo: "/img/boogiebounce.jpg"
      bio: "For runners only - a warm up excercises from Boogie Bounce!"
      company: "Boogie Bounce"
      link:
        href: "http://www.boogiebounce.com/cadnam-southampton-so40"
        text: "Boogie Bounce"
      presentation:
        title: "Santacise"
        description: "For runners only - a warm excercise from Boogie Bounce!"
        time: "9h00"
    - name: "Run starts and Christmas Fayre doors open"
      bio: "For runners only - a warm excercise from Boogie Bounce!"
      presentation:
        title: "Run starts and Christmas Fayre opens"
        description: "If you are running then go...\n
        ...If not then browse"
        time: "9h30"
    - name: "Santacise with Boogie Bounce Southampton"
      photo: "/img/oceanharmony.png"
      bio: "Ocean Harmony's Barbershop chorus performance"
      company: "Ocean Harmony"
      link:
        href: "https://oceanharmony.co.uk/"
        text: "Ocean Harmony"
      presentation:
        title: "Ocean Harmony"
        description: "Ocean Harmony's Barbershop chorus performance"
        time: "10h00"
    - name: "Roverang Alumni Choir"
      photo: "/img/roverang.png"
      bio: "Roverang Alumni Choir Performance"
      presentation:
        title: "Roverang Alumni Choir"
        description: "Choir performance"
        time: "11h00"
    - name: "Santa Selfies"
      presentation:
        title: "Santa Selfies"
        description: "Get a picture of yourself with the big man himself!"
        time: "11h00"
    - name: "Mince Pie eating Competition"
      bio: "Mince Pie eating Competition"
      presentation:
        title: "Mince Pie eating Competition"
        description: "Mince Pie eating Competition"
        time: "12h00"
    - name: "Result of The Great Totton Cake Off"
      photo: "/img/cakeoff18.png"
      bio: "Result of The Great Totton Cake Off"
      link:
        href: "http://www.boogiebounce.com/cadnam-southampton-so40"
        text: "Result of The Great Totton Cake Off"
      presentation:
        title: "Result of The Great Totton Cake Off"
        description: "Result of The Great Totton Cake Off"
        time: "12h10"
  # 12:30 The raffle is drawn (who will win this year’s hamper?)
    - name: "The raffle draw - who will win this years hamper?"
      presentation:
        title: "The raffle draw - who will win this years hamper?"
        description: "The raffle draw - who will win this years hamper?"
        time: "12h30"
